### ISSUE TITLE
Is there a way to automatize numbering of figure/tables in the notebook?

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#11]

**Comment by zelenkastiot** [comment]
I think that the figures are automatically numbered (Check [this](https://jupyterbook.org/content/figures.html#figures) for a better explanation). Just use this code: 

````{figure} ../images/C-3PO_droid.png
---
height: 150px
name: directive-fig
---
Here is my figure caption!
````

And the output is for example: 
![image](https://user-images.githubusercontent.com/37374247/127174554-65eecfd4-4d44-420b-a4f9-91944b144ce3.png)

**Comment by jcohenadad** [comment]
Thank you @zelenkastiot we can close then
