### ISSUE TITLE
Is there a way to manage references in a book?

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#12]

**Comment by zelenkastiot** [comment]
Yes, there is in the new versions. But I haven't used it yet. I can try tough. Check [this](https://jupyterbook.org/content/citations.html?highlight=references) out

**Comment by jcohenadad** [comment]
@alexfoias do you mind taking this over?

**Comment by alexfoias** [comment]
sure I can work on it. Where do we have the references ?

**Comment by alexfoias** [comment]
Can one of you please assign me to the issue ? thanks.

**Comment by jcohenadad** [comment]
> sure I can work on it. Where do we have the references ?

So, currently there are only 1-2 references listed because I still need to write the article 😅 
But you can already give it a try. I've hard-coded the URL of the refs [here](https://courtois-neuromod.github.io/anat-processing-book/introduction/introduction.html).

**Comment by alexfoias** [comment]
@jcohenadad who should I pass this issue to ?

**Comment by jcohenadad** [comment]
> @jcohenadad who should I pass this issue to ?

no need to always assign someone, just deassign yourself
