### ISSUE TITLE
How to build the notebook locally?

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#13]
Is there a way to build the notebook locally? It would be easier than to edit the notebook on internet

**Comment by mathieuboudreau** [comment]
Can you clarify if you mean *use the notebook locally* or *build the jupyter book locally&?

If it's the first, yes I think you should be able to if you have Docker installed on your computer and use [repo2docker](https://github.com/jupyterhub/repo2docker) to generate & launch the docker file. @agahkarakuzu has more experience in doing this locally, so he can advise further.

**Comment by mathieuboudreau** [comment]
Though if I recall correctly, I think Agah is offline today and tomorrow, so if this is urgent I could re-try to install Docker on my laptop (I believe it's been made M1-compatible) and give it a shot, and if it works send you instructions.

**Comment by jcohenadad** [comment]
I think this is what i was looking for: https://github.com/jupyter/notebook#installation

**Comment by jcohenadad** [comment]
i'll document in the readme how to build locally

**Comment by jcohenadad** [comment]
I see that the folder "_build" is present in the repository. Is this normal? For example with RTD the build is done by RTD backend and then the _build/html/index.html is exposed by the server hosting the website. 

In this case, I assume Github is hosting the website, but cannot Github do the build as well? That would prevent duplicating the source and the built images.

**Comment by mathieuboudreau** [comment]
I know Jupyter Books could be built by GitHub previously, but they change their whole infrastructure so often that I've lost track if their more recent version has made that more difficult. @zelenkastiot can provide input on the current version I think.

**Comment by zelenkastiot** [comment]
So the steps (for build explained in more detail [here](https://jupyterbook.org/start/build.html), for deployment [here](https://jupyterbook.org/start/publish.html)) for building and deploying the book are: 
- Run and save notebook locally 
- With prompt go outside the book, for example <code>book_demo</code> is the folder contatining the notebooks/markdown files. Go outside the <code>book_demo</code> and use `jb build book_demo`
- Then go inside the <code>book_demo</code>
- Add the folders to the remote repo, commit, push
- Install <code>ghp-import</code> with pip ( `pip install ghp-import`)
- Use the following command to deploy to <code>gh-pages</code> branch: `ghp-import -n -p -f _build/html`

**Comment by agahkarakuzu** [comment]
@jcohenadad there should be a GitHub action that triggers an html build (sphynx based) and pushes built sources to the gh-pages branch for serving the book.

The above assumes that the notebook outputs are saved by the user. It does not execute the whole notebook to regenerate outputs in book's environment (numpy, plotly etc). That's something we can do with Neurolibre :) 

Bottomline, provided that the outputs are rendered and saved inside the ipynb, building and publishing book is pretty straightforward.

**Comment by jcohenadad** [comment]
> @jcohenadad there should be a GitHub action that triggers an html build (sphynx based) and pushes built sources to the gh-pages branch for serving the book.
> 
> The above assumes that the notebook outputs are saved by the user. It does not execute the whole notebook to regenerate outputs in book's environment (numpy, plotly etc). That's something we can do with Neurolibre :)
> 
> Bottomline, provided that the outputs are rendered and saved inside the ipynb, building and publishing book is pretty straightforward.

thank you @agahkarakuzu for chipping in-- i would find it more elegant to have a GH action deploy the website for us. @zelenkastiot is this something you can work on? If you don't have the time, no worries i'll find someone else

**Comment by agahkarakuzu** [comment]
@zelenkastiot github action requires adding someone's token with push access. Let me know when you need it if you undertake this task.

**Comment by jcohenadad** [comment]
I added the documentation to install and build the notebook locally in 76046f3521387fab532edb343c34fe2eaf60b9fe

**Comment by jcohenadad** [comment]
> thank you @agahkarakuzu for chipping in-- i would find it more elegant to have a GH action deploy the website for us. @zelenkastiot is this something you can work on? If you don't have the time, no worries i'll find someone else

redirected to #15 
we can close this issue
