### ISSUE TITLE
spinalcord_results/ should be fetched from the release, not put under the repository

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#14]
Currently, CSV results are sitting in this repository. It is not elegant (duplication) and prone to error.

Ideally, the code would fetch the CSV results directly from the GH release assets (eg: https://github.com/courtois-neuromod/anat-processing/releases/tag/r20210610). But, is this possible with notebook?  IIUC we need to provide ALL the sources, so maybe not possible...

or as a workaround, we could potentially have the GH action deployment script fetch those before the build...?

**Comment by zelenkastiot** [comment]
Hi @jcohenadad, so the thing is that file was there by accident.  Earlier this morning I added locally to fix the issues and left them there. In the binder session I am downloading them and unzipping them with the <code><a href="https://github.com/courtois-neuromod/anat-processing-book/blob/main/postBuild#L1">postBuild</a></code>: 



```
wget -O spinalcord_results.zip https://github.com/courtois-neuromod/anat-processing/releases/download/r20210610/spinalcord_results.zip 
unzip -j spinalcord_results.zip -d $HOME/spinalcord_results/
```

**Comment by jcohenadad** [comment]
Indeed, I understand now that it is _not_ in the repos, but fetched by the post build. However, if we want full reproducibility of the jupyter notebook, we need the data to be fetched _inside_ the notebook.
