### ISSUE TITLE
Automatically build the Jupyter book using Github actions

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#15]
- [x] Implement automatic build using github actions. See https://github.com/courtois-neuromod/anat-processing-book/issues/13#issuecomment-887595960
- [x] Once the automatic build is implemented we should add "_build" in the .gitignore file ASAP, so we minimize fat accumulation in the repos

**Comment by jcohenadad** [comment]
@agahkarakuzu do you think you could help with this?

**Comment by agahkarakuzu** [comment]
I'll look into this @jcohenadad

**Comment by agahkarakuzu** [comment]
@jcohenadad can you please add a repo-scoped personal access token to this repo named `GHA_PAT` ? Looks like I don't have privileges to do so.

**Comment by jcohenadad** [comment]
> @jcohenadad can you please add a repo-scoped personal access token to this repo named `GHA_PAT` ? Looks like I don't have privileges to do so.

i added you as admin:
![image](https://user-images.githubusercontent.com/2482071/127691712-3a851794-9655-488b-8091-6b00f3193933.png)

**Comment by agahkarakuzu** [comment]
Thank you Julien, I'll implement this today. @zelenkastiot can I count on that the notebooks in the source folder are saved with outputs, otherwise my attempts will ruin gh-pages content.

**Comment by agahkarakuzu** [comment]
I set the GitHub actions and ignored _build from git history. #37 

It is working, the page is rendered properly, will be triggered on each push to the `main`, you can see the builds, successful from the get go:

https://github.com/courtois-neuromod/anat-processing-book/actions

**Comment by jcohenadad** [comment]
fixed in #37
