### ISSUE TITLE
add comments in the _config.yml

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#17]
this file has comments-- it is VERY useful: https://github.com/naturalistic-data-analysis/naturalistic_data_analysis/blob/master/_config.yml

we should do it as well

**Comment by zelenkastiot** [comment]
Sure thing, will include them in the next build.

**Comment by zelenkastiot** [comment]
I added comments in the newest build 😄

**Comment by jcohenadad** [comment]
> I added comments in the newest build 😄

Brilliant! For the record, comments were added in 150eea141e7cb34d07059b6e6c10332127770dae

@zelenkastiot in the future can you please refer to the exact commit when you address an issue? In general we work with PRs, but in this case we are in a rush so we push to master directly so we need to have a reliable and convenient way to inspect changes made to the repos. Thank you.
