### ISSUE TITLE
How results are fetched now that `spinalcord_results/` was removed

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#19]
After b2b2046823ec75a17c697252e27adf4154d3d558 (see context: https://github.com/courtois-neuromod/anat-processing-book/issues/14), the folder "spinalcord_results/" was removed.

However, when building the documentation _locally_, even though the folder is not there, the plots are properly generated:

![Screen Shot 2021-07-28 at 9 58 16 AM](https://user-images.githubusercontent.com/2482071/127336132-bd79dd1e-c0c1-4c4a-98e8-712ad8501c4d.png)

So, strangely, the CSV files are fetched there: :"./../spinalcord_results/csa-SC_T1w.csv" but they are _not_ there. What is this magic??

Also: I made sure it was not a cache thing by running the book in an incognito mode in my browser.

**Comment by zelenkastiot** [comment]
So the trick is that the plot is cached inside the notebook. When you build it, you go from the existing notebook to an HTML you do not run the notebook. 

If you try to run it, in a jupyter notebook interface then you will run into an error of missing data, but if you build the book it will always show it. 

That's how we resolve not having the data in the repo. We run the plots locally with the results, build the book, and when we push we remove the results. Then in the binder/colab environment I elegantly download the releases (explained like #14 )

**Comment by jcohenadad** [comment]
I see, but when I build the book locally using [these instructions](https://github.com/courtois-neuromod/anat-processing-book#build-the-notebook-locally), how come it can fetch the data?

**Comment by zelenkastiot** [comment]
I am a Windows user, but of my humble bash knowledge: 

1. `chmod +x postBuild`
2. `./postBuild`

Should work for Linux, Mac

**Comment by jcohenadad** [comment]
> I just re-read the question: so it is downloading the data?

I don't think it does, hence my misunderstanding of the whole process 😅 

<details><summary>Terminal output of the build</summary>

```console
julien-macbook:~/code/neuromod/anat-processing-book $ jupyter-book build source/ --path-output _build
Running Jupyter-Book v0.10.0
Source Folder: /Users/julien/code/neuromod/anat-processing-book/source
Config Path: /Users/julien/code/neuromod/anat-processing-book/source/_config.yml
Output Path: _build/_build/html
Running Sphinx v3.5.4
making output directory... done
myst v0.13.7: MdParserConfig(renderer='sphinx', commonmark_only=False, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, update_mathjax=True, enable_extensions=['html_image', 'amsmath', 'colon_fence', 'deflist', 'dollarmath', 'html_admonition', 'linkify', 'replacements', 'smartquotes', 'substitution'], disable_syntax=[], url_schemes=['mailto', 'http', 'https'], heading_anchors=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'])
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 4 source files that are out of date
updating environment: [new config] 4 added, 0 changed, 0 removed
reading sources... [100%] results/2-test                                                            
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] results/2-test                                                             
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/_build/html.

===============================================================================

Finished generating HTML for book.
Your book's HTML pages are here:
    _build/_build/html/
You can look at your book by opening this file in a browser:
    _build/_build/html/index.html
Or paste this line directly into your browser bar:
    file:///Users/julien/code/neuromod/anat-processing-book/_build/_build/html/index.html            

===============================================================================

```

</details>

And these commands don't return anything:
~~~
find . -name "spinalcord_results"
find $HOME -name "spinalcord_results"
~~~

**Comment by jcohenadad** [comment]
The reason results appear is because they are _not_ generated by the build, but are _already_ sitting in the jupyter notebook which is already in the repository: source/results/1-test.ipynb
