### ISSUE TITLE
README put by mistake?

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#21]
https://github.com/courtois-neuromod/anat-processing-book/blob/main/source/results/README.md

**Comment by zelenkastiot** [comment]
Hi @jcohenadad, according to the commit log you have added the file. Should I delete it?

**Comment by jcohenadad** [comment]
> Hi @jcohenadad, according to the commit log you have added the file. Should I delete it?

it was already there before, i just moved it in bc48ae65029201f3f88697de87623bd19c364831 when reorganizing the folder structure:
![image](https://user-images.githubusercontent.com/2482071/127656962-69de7b5f-889e-47ea-b2d3-79a778dd8f08.png)

so yes, i guess you can delete it if it was put by mistake at the first place

**Comment by zelenkastiot** [comment]
Issue resolved with: 209578d9e0087ea77898e10752d9d75ce3dd747f

**Comment by jcohenadad** [comment]
Small comment: https://github.com/courtois-neuromod/anat-processing-book/commit/209578d9e0087ea77898e10752d9d75ce3dd747f includes many other changes, making it difficult to review the commit. In the future please only include few and isolated changes in commits

**Comment by zelenkastiot** [comment]
Sorry, I realized when I was pushing that I changed multiple things. Won't happen in the future
