### ISSUE TITLE
HTML in source?

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#22]
i found this: https://github.com/courtois-neuromod/anat-processing-book/blob/main/source/results/new-fig-2.html

i thought the HTML material was only in the built (not source) folder?

**Comment by zelenkastiot** [comment]
Hi @jcohenadad, this is the output that is seen inside the cell. The plotly <code>plot</code> function from the ploty.offline save outputs as HTML and we store that in the notebook.

**Comment by jcohenadad** [comment]
Isn't that something that we can generate on the fly before shipping all the content to the server hosting the book? related to #15
