### ISSUE TITLE
Why "-2"?

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#25]
Here: https://github.com/courtois-neuromod/anat-processing-book/blob/main/source/results/1-test.ipynb

![image](https://user-images.githubusercontent.com/2482071/127667162-aca379ce-e155-4883-8a9f-06f4318f4281.png)

**Comment by jcohenadad** [comment]
After discussion, the "-2" should _not_ be there.

**Comment by zelenkastiot** [comment]
Issue resolved with: 209578d9e0087ea77898e10752d9d75ce3dd747f

**Comment by jcohenadad** [comment]
The commit includes many other changes, making it difficult to review
