### ISSUE TITLE
Should notebooks have the outputs?

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#27]
Currently the notebooks (eg: 1-test.ipynb) include the outputs, which adds fat to the repository. Is this necessary given that the HTML should be generated by the build?

**Comment by jcohenadad** [comment]
After discussion with the team, we decided to remove the outputs from the notebooks. However, the plots are _included_ in the notebooks, which is why they are 3-4MB. If we clear the output and build the book locally, the plots won't be rendered anymore.

So the strategy we should do is:
- execute the jupyter notebook (either manually or with GH action)
- build the jupyter book --> it will create the required HTML (standalone) under `_build/html/`
- clear the output of the jupyter notebook
- git commit everything (including the `_build/html/`)
  - the problem with that is that it includes large files. This will be solved once we deploy to GH pages with GH actions #15

**Comment by mathieuboudreau** [comment]
In the V2 branch, I found a better strategy which resolves this.

Cells with outputs (excluding the figure plotting cell) can hide input by using the [cell tags `hide-output`](https://jupyterbook.org/en/stable/content/metadata.html). This way, notebooks can be saved with outputs cleared (leading to minimial file size), and the GitHub actions build will automatically run the cells prior to generating the HTML, and hide the outputs from the cells with that tag (won't show up in the HTML).

See this in in the V2 book version, in the sections "New Pages": https://courtois-neuromod.github.io/anat-processing-book/results-new.html. This link will be deprecated later though, so below are some screenshots:

<img width="1417" alt="Screen Shot 2022-06-07 at 11 01 42 AM" src="https://user-images.githubusercontent.com/1421029/172399900-e8abab51-7c42-4ebb-81a9-894e474cae5f.png">

<img width="1417" alt="Screen Shot 2022-06-07 at 11 01 53 AM" src="https://user-images.githubusercontent.com/1421029/172399929-ac7eddd6-ace4-402c-9493-3aff59880aec.png">

<img width="1417" alt="Screen Shot 2022-06-07 at 11 02 01 AM" src="https://user-images.githubusercontent.com/1421029/172399953-4a33860a-caa4-46c7-897f-387313673f94.png">
