### ISSUE TITLE
The code to generate the figures is complex and highly-customized

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#29]
I know we won't solve this issue for the current book, but I wanted to raise this issue: I wanted to reuse the code to make other figures, but the code is currently extremely complicated and highly customized (ie: hard-coded number of subjects, etc.).

I would like very much to see is simplified.

**Comment by mathieuboudreau** [comment]
Working on in V2

**Comment by mathieuboudreau** [comment]
Resolved in the version 2 release
