### ISSUE TITLE
Feedback on notebook

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#3]
Here is some feedback on notebook commit 01fb76a6dfc1ef322f37ddd8f63e6c210c091b36

- General comment: great start! The layout is beautiful and intuitive. Great job!
- Under logo change "Spinal cord analysis" for "Anatomical analysis"

Note that i've created an account to Hypothesis so I also annotated directly on the notebook (very convenient!). I've also opened PR when changes were on the MD file.

**Comment by zelenkastiot** [comment]
Hello @jcohenadad, 

I managed to: 
- merge the PR 
- rebuild the book with the modified intro and title 
- removed the csv display
- modify all of the changes from the Hypothesis comments regarding the plots 

Please let me know if I did everything correctly. [Here](https://courtois-neuromod.github.io/anat-processing-book/01/1-test.html) is the link to the notebook

**Comment by jcohenadad** [comment]
> Please let me know if I did everything correctly. Here is the link to the notebook

beautiful! i've added more comments/opened issues. I think we can close this issue which is no more specific.
