### ISSUE TITLE
Remove all "mean" mentions in the legend

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#40]
In plots like this one:
![image](https://user-images.githubusercontent.com/2482071/131144474-3192f008-89d3-4bc7-9287-6faec9d0d8c6.png)

We don't need to add the 'mean' in the legend. We will simply mention it in the figure caption (along with an explanation about the STD).

**Comment by mathieuboudreau** [comment]
@zelenkastiot can you handle this issue?
