### ISSUE TITLE
Automatically build notebook with Github Actions

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#41]
After #15, the book is automatically built (which is great!).

However, when we make a change to the notebook, we still have to build it locally. It would be great if this step would also be automatized.

Note: the build of the notebook would need to be done _before_ building the book.

Possibly useful resource: https://github.com/marketplace/actions/run-notebook

Related to #27

**Comment by mathieuboudreau** [comment]
@agahkarakuzu do you know if this would be possible? (i.e. executing the Jupyter Notebook with GitHub actions prior to the book build, so that we can push cleared notebooks?)
