### ISSUE TITLE
Add horizontal light lines at yticks on plots

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#7]
![image](https://user-images.githubusercontent.com/2482071/124514990-54197500-ddac-11eb-94d9-f8d28343fbd1.png)

Adding horizontal lines as done here would help:
![image](https://user-images.githubusercontent.com/2482071/124515024-65628180-ddac-11eb-9701-250ca4f487cd.png)

**Comment by zelenkastiot** [comment]
@jcohenadad that was primarily what I intended to do with the red line from #6. I can modify it to black and add a name for it in the legend? How should I reference it

**Comment by jcohenadad** [comment]
ah! now i understand the confusion. I was referring to the horizontal lines at the yticks (red arrows):
![124515024-65628180-ddac-11eb-9701-250ca4f487cd](https://user-images.githubusercontent.com/2482071/124529689-1d0d8880-ddd9-11eb-94e8-e7342a54ce97.png)

let's talk about the red dashed line in the other issue #6

**Comment by zelenkastiot** [comment]
They are like e default of the Plotly library, I usually remove them. Should I add them?

**Comment by jcohenadad** [comment]
hi @zelenkastiot, i was wondering if there was any update on this issue?

**Comment by zelenkastiot** [comment]
Since the two issues are overlapping I commented in #6 explaining the last local updates I worked on.

**Comment by jcohenadad** [comment]
Now implemented by the great @zelenkastiot 🚀
